name: LockIT
version: 1.4
main: com.stein.lockit.LockIT
api-version: 1.21
author: Stein
commands:
  lockit:
    description: Main command for LockIT
    usage: /lockit <universalkey|key|customkey <id>|lock <1-6>|lockpick|reload>
permissions:
  lockit.admin:
    description: Allows you to use the /lockit command
    default: op